### ISSUE TITLE
New name for `component`

### ISSUE THREAD

**Issue by paldepind** [funkia/funnel#23]
The `component` function needs a better name.

A few ideas from the top of my head

* `createComponent`
* `modelView`
* `createModelViewComponent`
* `mvComonent`
* `statefulComponent`
* `controllerComponent`

**Comment by limemloh** [comment]
I agree that it needs another name, something more describing than just component. Ideally the name should make the difference between this and `loop` more obvious.
I think your suggestion `modelView` is a good name.

**Comment by paldepind** [comment]
I think I prefer `controllerComponent`. It's inspired by what they call "controller components" in React-land. I think it expresses nicely that it creates components that can have complex logic, state, and side-effects.
